const blogData = [
    {
      id: 1,
      title: "Modern Villas",
      description: "Explore spacious, contemporary villas designed for luxury and comfort with cutting-edge features.",
      img: "https://via.placeholder.com/400x300?text=Modern+Villas",
      link: "/blogs/modern-villas",
    },
    {
      id: 2,
      title: "Cozy Pods",
      description: "Compact yet elegant, our pods redefine small-space living with exceptional style and functionality.",
      img: "https://via.placeholder.com/400x300?text=Cozy+Pods",
      link: "/blogs/cozy-pods",
    },
    {
      id: 3,
      title: "Designer Studios",
      description: "Create a personalized workspace or creative studio with our bespoke designer solutions.",
      img: "https://via.placeholder.com/400x300?text=Designer+Studios",
      link: "/blogs/designer-studios",
    },
    {
      id: 4,
      title: "Eco-Friendly Living",
      description: "Sustainability meets luxury in our eco-friendly villa and pod designs.",
      img: "https://via.placeholder.com/400x300?text=Eco-Friendly+Living",
      link: "/blogs/eco-friendly-living",
    },
    {
      id: 5,
      title: "Balinese Retreat",
      description: "Experience the tranquility of Bali with villas inspired by traditional Balinese architecture.",
      img: "https://via.placeholder.com/400x300?text=Balinese+Retreat",
      link: "/blogs/balinese-retreat",
    },
    {
      id: 6,
      title: "Luxury Interiors",
      description: "Discover premium interior designs crafted to elevate your living experience.",
      img: "https://via.placeholder.com/400x300?text=Luxury+Interiors",
      link: "/blogs/luxury-interiors",
    },
    {
      id: 7,
      title: "Outdoor Living Spaces",
      description: "Maximize your outdoor area with stylish and functional living spaces.",
      img: "https://via.placeholder.com/400x300?text=Outdoor+Living+Spaces",
      link: "/blogs/outdoor-living-spaces",
    },
    {
      id: 8,
      title: "Urban Pods",
      description: "Perfect for city living, our urban pods combine style and practicality in a compact design.",
      img: "https://via.placeholder.com/400x300?text=Urban+Pods",
      link: "/blogs/urban-pods",
    },
    {
      id: 9,
      title: "Smart Home Integration",
      description: "Transform your home with cutting-edge smart technology for a connected lifestyle.",
      img: "https://via.placeholder.com/400x300?text=Smart+Home+Integration",
      link: "/blogs/smart-home-integration",
    },
    {
      id: 10,
      title: "Mountain Retreats",
      description: "Breathe in the serenity of nature with our mountain-inspired villa designs.",
      img: "https://via.placeholder.com/400x300?text=Mountain+Retreats",
      link: "/blogs/mountain-retreats",
    },
    {
      id: 11,
      title: "Modular Homes",
      description: "Explore modular homes that offer flexibility, durability, and contemporary design.",
      img: "https://via.placeholder.com/400x300?text=Modular+Homes",
      link: "/blogs/modular-homes",
    },
    {
      id: 12,
      title: "Beachfront Villas",
      description: "Enjoy breathtaking ocean views with our luxurious beachfront villa designs.",
      img: "https://via.placeholder.com/400x300?text=Beachfront+Villas",
      link: "/blogs/beachfront-villas",
    },
    {
      id: 13,
      title: "Artistic Studios",
      description: "Infuse your workspace with creativity using our art-inspired studio designs.",
      img: "https://via.placeholder.com/400x300?text=Artistic+Studios",
      link: "/blogs/artistic-studios",
    },
    {
      id: 14,
      title: "Tiny Homes",
      description: "Compact yet luxurious, our tiny homes are designed for efficiency and style.",
      img: "https://via.placeholder.com/400x300?text=Tiny+Homes",
      link: "/blogs/tiny-homes",
    },
    {
      id: 15,
      title: "Rustic Charm Villas",
      description: "Step back in time with villas that exude rustic charm and timeless beauty.",
      img: "https://via.placeholder.com/400x300?text=Rustic+Charm+Villas",
      link: "/blogs/rustic-charm-villas",
    },
  ];
  
  export default blogData;
  