const mulberryArt = [
    {
    img_link:"https://mulberryprefab.com/wp-content/uploads/elementor/thumbs/5-2-qn6hz9v459k5o83zv9nnkpxaptp5h78kj7o0bqhchc.webp",
    title:"Rumah Clover",
    id:"Rumah-Clover",
    p1:"The Balinese Chalet Series Villa by Mulberry is designed to offer an authentic experience of a tropical resort. An ode to the architecture of Bali, the villa delicately balances modern-day luxuries with traditional design principles. This three-bedroom luxury villa spread across 3100 Sq.ft. draws inspiration from the design principles used in traditional Balinese architecture. Spatially planned on the ‘tri mandala’ philosophy of ancient Bali, a sprawling open pavilion heralds visitors into the 500 Sq.ft. living area. Indoor courtyards and tropical foliage tucked into the pockets of the villa unify the home with nature. Exquisite decks for each bedroom, the alfresco shower experience, and the cosy dining area along the expansive swimming pool are a testimony to the indoor-outdoor living construct of a traditional Bali home. Taking clues from nature, the roof takes the form of a leaf. Large overhangs envelop the seating shacks on the semi-open deck, offering a quiet, meditative alcove with a sweeping view of the pool.",
    p2:"The louvred doors along these decks bring in gusts of fresh air while maintaining the residents’ privacy. In favour of bringing nature indoors, the earthy-toned natural material palettes impart a sense of relaxation and quiet to the bedrooms.",
    p3:"Pristine white walls create a beautiful contrast with the wooden and stone accents, breathing luxury into the villa. The soft upholstery and indoor plants softly complement the natural, raw interior finishes.",
    p4:"The design of the villa captures the true essence of the island. Imbibing the traditional architectural principles and carefully crafted details, the estate is a portal to the tropical paradise of Bali.",
    technical_details:"https://mulberryprefab.com/wp-content/uploads/2024/04/Rumah_Clover.webp",
    layout:"3Bed, 3Bath",
    Built_up_Area:"3018.2 Sq.ft.",
    Deck_Area:"2296.37 Sq.ft.",
    Total_Area:"5314.57 Sq.ft.",
    Architectural_Style:"Balinese",
    Series:"Timeless Edition 1 – Endless Summer Vibes",
    type:"Ground Floor",
    Timeline:"25 Weeks",
    Recommended_Size:"Around 15,943.7 Sq/ft.",
    Green_Quotient:"80/100",
    Durability:"2 Times Stronger Than Traditional Construction",
    Detail:"src/Container/image/Rumah clover.png"
},
{
    img_link:"https://mulberryprefab.com/wp-content/uploads/elementor/thumbs/6-1-qn6idh7bf50543h8xeop94w1vfotsjmjtik5e9f6gg.webp",
    title:"The Hideaway",
    id:"The-Hideaway",
    p1:"A modern take on the tropical home, the villa uses design elements, materials and finishes of Hawaiian architecture. Spread across 2760 Sq.ft. of area, this luxury abode is designed to evoke a sense of relaxation and excitement.",
    p2:"Drawing inspiration from the sloping roofs of a typical Hawaiian villa, the terracotta-clad exterior walls make a bold statement. These walls are delicately juxtaposed with the wooden deck and concrete-finished walls, standing tall, like those of a sanctuary.A grand wooden door and muted walls greet visitors at the entrance,  setting the tone of the villa – striking and luxurious. The double-height living room is flanked by the dining room and a bedroom on one side and two bedrooms on the other.",
    p3:"During the day, the living room changes its moods as dramatic sun’s rays permeate the space through the skylight. The low-seating dining room by the pond is a nod to ‘ohana’, which means family, an inherent part of the Hawaiian culture. Overlooking the infinity pool, the outdoor dining area is a relaxing spot to enjoy a meal, while the expansive wooden deck is perfect for soaking up in the sun and appreciate the view. The raw, exposed interior finishes in the interiors in harmony with the exteriors blur the lines between the built and unbuilt, offering a connection of the outdoor with the villa.",
    p4:"Contemporary on the first impression, the villa’s design has its roots in the island’s authentic architecture, history, and culture. A radical interpretation of the traditional Hawaiian villa, the design is sure to make heads turn.",
    technical_details:"https://mulberryprefab.com/wp-content/uploads/2024/04/The_Hideaway-1.webp",
    layout:"3 Bed, 3 Bath",
    Built_up_Area:"3713.55 Sq. ft.",
    Deck_Area:"1585 Sq. ft.",
    Total_Area:"5298.55 Sq. ft.",
    Architectural_Style:"Hawaiian",
    Series:"Timeless Edition 1 – Tropical  Tints",
    type:"Ground Floor",
    Timeline:"25 Weeks",
    Green_Quotient:"80/100",
    Recommended_Size:"Around 15,895.5 Sq.ft",
    Durability:"2 Times Stronger Than Traditional Construction",
    Detail:"src/Container/image/the hideway.png"
},
{
    img_link:"https://mulberryprefab.com/wp-content/uploads/elementor/thumbs/4-3-qn6l4qxp78wb9ja79bg9l32keeecprq0suw80a8dbk.webp",
    title:"Villa Essenica",
    id:"Villa-Essenica",
    p1:"A modern manifestation of traditional Spanish elegance, this villa exudes a sense of warmth and relaxation. Natural finishes, ornamental details and outdoor spaces with a dash of extravagance make this villa a beautiful Mediterranean dream. Clad in terracotta tiles, the staggered roof strikes a balance with the white stucco walls. The villa is planned on a circular layout circumscribed by an infinity pool, across 6200 Sq.ft. The double-height, semi-circular arch at the entrance porch defines the grandeur and splendour that follows, while the upside-down arches are an unexpected visual treat.",
    p2:"On the ground floor, the entrance lobby separates the living room, kitchen and dining areas form the two bedrooms, a library and an activity room, allowing privacy to residents. The first floor houses two bedrooms and an office. ",
    p3:" A pergola-covered walkway traces the central courtyard and pond. The balcony on the first floor overlooks this courtyard and is framed by the offbeat inverted arches. The spa tub on the deck along the swimming pool and the outdoor dining area are invitations to relax and unwind. The arched openings frame the views of the pool and sprawling landscape.",
    p4:"Thoughtful details like hand-painted tiles, bespoke furniture and accent walls add life to the spaces, seamlessly blending the contemporary and traditional.This villa series by Mulberry pays homage to the art and architecture of Spain and radiates the mirth and exuberance of a Spanish ‘fiesta’. From a quiet reading nook to a pool-side dance floor, the villa promises a corner for everyone, striking a balance between work, play and leisure.",
    technical_details:"https://mulberryprefab.com/wp-content/uploads/2024/04/3i_Villa_Escenica_Ground_Floor-1.webp",
    layout:"4 Bed, 4 Bath",
    Built_up_Area:"7204.2 Sq.ft.",
    Deck_Area:"3879.9 Sq.ft.",
    Total_Area:"11084.1 Sq.ft.",
    Architectural_Style:"Spanish",
    Series:"Timeless Edition 1 – Mediterranean BluesGround +1 Floor",
    Timeline:"20 Weeks",
    Green_Quotient:"80/100",
    Recommended_Size:"Around 31,335 Sq.ft.",
    Durability:"2 Times Stronger Than  Traditional Construction",
    Detail:"src/Container/image/Villa Essenica.png"
},
{
    img_link:"https://mulberryprefab.com/wp-content/uploads/elementor/thumbs/6-qn6kmpf80q76ezhnm0p284z1x5bpyx3hzk3pe2zer4.webp",
    title:"De Arte House",
    id:"De-Arte-House",
    p1:"With 3600 Sq.ft. of refined luxury, the Spanish Villa series embodies the craft, tradition and charm of authentic Spanish architecture. This modern home takes an elegant, asymmetric form with vaulted roofs, arched windows, and plush interiors. Delicately blending Spanish art and architecture, the full-height, stained-glass windows are designed to captivate passers-by.",
    p2:"Welcoming visitors in, the inclined arched entrance is flanked stairways that lead to the rooftop terrace. The glass slits allow filtered light into the landscape pockets. The entrance foyer is the axis that brings the other spaces in the home together. The living area, kitchen,  dining room and deck on one end of this axis are enveloped by a 25-feet lofty, vaulted roof that reduces direct heat gain. Tinted rays of light in shades of pink and blue bounce off the white stucco walls, adding a touch of art and drama. Framed by the stairways, the caved semi-open pool extends outdoor and is like a gateway to the Mediterranean waters of Spain. Overlooking the pool are the study room and kitchen garden.",
    p3:"The other side of the axis houses two bedrooms, a bar and a home theatre on theground floor, and two bedrooms on the first floor. The staircase is intricatelydesigned with hand-painted Spanish tiles, wooden finishes and fine details. The understated yet sophisticated interiors perfectly  complement the avant-garde exteriors of the villa.",
    p4:"Functionality, form and aesthetics go hand in hand at the ultra-stylish home. An eclectic mix of traditional Mediterranean architecture and modern art, the villa is designed to offer fineness and comfort to its residents.",
    technical_details:"https://mulberryprefab.com/wp-content/uploads/2024/04/ii_De-Arte-House_First-Floor-1.webp",
    layout:"4Bed, 4Bath",
    Built_up_Area:"5190 Sq.ft.",
    Deck_Area:"1320 Sq.ft.",
    Total_Area:"6500 Sq.ft.",
    Architectural_Style:"Spanish",
    Series:"Timeless Edition 1 – Mediterranean Blues Ground +1 Floor",
    Timeline:"20 Weeks",
    Green_Quotient:"80/100",
    Recommended_Size:"Around 19,697.94 Sq. ft.",
    Durability:"2 Times Stronger Than Traditional Construction",
    Detail:"src/Container/image/De Arte House.png"
},
{
    img_link:"https://mulberryprefab.com/wp-content/uploads/2024/04/Tranquil-Cove.webp",
    title:"Tranquil Cove",
    id:"Tranquil-Cove",
    p1:"True to Hawaiian architecture, this series of villas is designed to reminisce, relax, and connect with nature. The exteriors of the villa reflect the  architecture of the tropical island with its wide-hipped roof, terracotta cladding and natural finishes. Traditional Hawaiian materials like wooden shingles and bamboo, red fire clay bricks, stone and wood add authenticity to the its architecture style. In addition, the extended roof overhangs, a typical characteristic of a Hawaiian villa, ensure a comfortable time outdoors, keeping harsh sunlight and rain at bay.",
    p2:"The expansive portico at the entrance offers an outdoor space to rest and unwind while extending into the sky-lit foyer. Bouncing off the still waters of the indoor pond, the soft, filtered light fills the space, creating a warm, inviting ambience. While the master bedroom overlooks this space, the bedroom enjoys a courtyard view. A sky-lit courtyard manifests itself at the heart of the villa, unifying the spaces. The spacious living and dining rooms also enjoy the pool’s view. ",
    p3:" The large volumes of the indoor spaces perfectly balanced with plush interiors, bespoke furniture and natural finishes connote luxury, grandeur establishing a connection to nature. The white, textured walls across the villa offer a calm and soothing aura while reflecting the abundant natural light. The vertical sliding window is another peculiar Hawaiian design element.",
    p4:"Bringing nature indoors, the design of this three-bedroom Hawaiian villa provides an abode to de-stress. The villa promises to transport your senses to the islands of Hawaii through its design, materials and atmosphere.",
    technical_details:"https://mulberryprefab.com/wp-content/uploads/2024/04/Tranquil_Cove-1-1.webp",
    layout:"2 Bed, 2 Bath",
    Built_up_Area:"2712 Sq. Ft.",
    Deck_Area:"2442 Sq. Ft.",
    Total_Area:"5154 Sq. Ft.",
    Architectural_Style:"Hawaiian",

    Series:"Timeless Edition 1 – Tropical Tints",
    Timeline:"20 Weeks",
    Green_Quotient:"80/100",
    type:"Ground Floor",
    Recommended_Size:"Around 12,109.41 Sq.ft.",
    Durability:"",
    Detail:"src/Container/image/tranquil cove.png"
},
{
    img_link:"https://mulberryprefab.com/wp-content/uploads/2024/04/Oakwood-Cottage.webp",
    title:"Oakwood cottage",
    id:"Oakwood-cottage",
    p1:"A container cabin that can be shipped anywhere— seems like an adventurous fantasy, right? This Oakwood Cottage beholds a sublime luxury that is flexible enough to travel with you! What marks its uniqueness is the seamless blend of these transportable pods that make themselves at home, wherever they’re placed. Whether you wish to enwrap the tranquility of the hills or the tingling of a flowing stream, this cabin is all you need by your side for a luxury retreat that promises peace and quietude.",
    p2:"A Box that Inspires! The portable 30’ x 60’ container cabin takes inspiration from the intricacy held within a simple box. Exuding luxury the expansive cabin takes you to newer heights of extraordinary with an accessible roof, soaking in the serenity.",
    p3:"A Balanced blend of Indoors and Outdoors Sprawling across an area of 632 sq. ft., the black wood and texture classing on the interiors complement the surroundings. Composed of a living room, kitchen, bedroom, bathroom, and deck, this prefabricated cabin is the perfect spot to stay connected with the natural world. The free-flowing spaces can conveniently nestle 2-3 residents. ",
    p4:"As one approaches the cabin, they’re welcomed with an accessible roof. You can either climb up for a seamless view of the surroundings or enter the world of contemporary aesthetics. The door opens up into a plush living room and kitchen adorned in a muted natural palette with wood and white paint being the dominant tones along with accents of glass. The private zone of the cabin is strategically accommodated at the end. The calming interiors open up to the balcony with a glass floor, adding a dynamic experience to interact with nature.  This container-inspired design incorporates the juxtapositions of indoors and outdoors. The earthy mood board creates a forest theme within the interiors. While the eclectic surroundings engulf you in its enigma. Whether you’re looking for a month-long workcation or a weekend getaway, this Oakwood Cottage offers a one-of-a-kind experience, you wouldn’t want to miss! This prefabricated structure with its rugged and rustic appeal offers a quick retreat from the urban hustle, allowing you to dissolve in nature as you cocoon into the world of comfort.",
    technical_details:"https://mulberryprefab.com/wp-content/uploads/2024/04/Oakwood_Cottage.webp",
    layout:"1Bed, 1Bath",
    Built_up_Area:"390.08 Sq.ft.",
    Deck_Area:"307.84 Sq.ft.",
    Total_Area:"700 Sq.ft.",
    Architectural_Style:"Contemporary",
    Series:"Glaming Pod",
    Timeline:"8 Weeks",
    Green_Quotient:"80/100",
    type:"Ground Floor",
    Recommended_Size:"Around 2,100 Sq/ft.",
    Durability:"2 Times Stronger Than Traditional Construction",
    Detail:"src/Container/image/Woods.png"
},
{
    img_link:"https://mulberryprefab.com/wp-content/uploads/2024/04/POOL-VIEW-1.webp",
    title:"Luum",
    id:"Luum",
    p1:"This luxurious Mexican villa takes a magnificent grip with symmetric charm. The Luum provides grandeur with harmony with proper geometry & ratios. Delicately blendsMexican art and architecture, the full-heightglass windows are designed to captivate passers-by. The boulders in the design adds to the aesthetic value defining the landscape of the villa.",
    p2:"A cosy invitation to visitors in, the narrow entrance gives sneak peek to the stairs outside. This entrance opens up to the grand living & dining space. The entrance foyer is the axis that brings the other spaces in the home together. The glass slits allow filtered light from the landscape pockets into the spaces. This framed opening from the living dining spaces open into the outer decks with pool. The deck has an intricately carved out staircase that leads you to the terrace thus drawing attention making it a focal point. ",
    p3:"The villa is spanned to have the four bedrooms at the four corners of the layout. Each room having its own green space with relaxing alfresco shower areas ensure a planned serendipity. The understated yet sophisticated interiors perfectly complement the bold outer façade of the villa. This makes it absolutely perfect to Relájate! ",
    p4:"Configuration with utilitarian design and elegance go hand in hand at the ultra-stylish home. An eclectic mix of modern art carved with Mexican niche, the villa is designed to offer brilliance and opulent comfort to its residents.",
    technical_details:"https://mulberryprefab.com/wp-content/uploads/2024/04/Oakwood_Cottage.webp",
    layout:"4BED, 5BATH",
    Built_up_Area:"3111SQ.FT",
    Deck_Area:"",
    Total_Area:"",
    Architectural_Style:"MEXICAN",
    Series:"BOHEMIAN RHAPSODY",
    Timeline:"",
    Green_Quotient:"80/100",
    type:"Ground Floor",
    Recommended_Size:"AROUND 9333SQ.FT ( 3 TIMES OF THE BUILT UP AREA)",
    Durability:" 2 TIMES STRONGER THAN TRADITIONAL CONSTRUCTION",
    Detail:"src/Container/image/Woods.png"
},
];
export default mulberryArt;